image: docker:latest
services:
    - docker:dind

stages:
    - base_image
    - sdk_bundles

# Expects $IMAGE which should be the name+tag of the registry image.
# Expects $OCI_YML variable which should be the path to the dockerfile
.base_template: &base_build
    tags:
        - aws
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull -f ${OCI_YML} -t ${IMAGE} .
        - echo ${IMAGE}
        - docker push ${IMAGE}
    only:
        - master
        - triggers
        - schedules

nightly:master:
    stage: base_image
    before_script:
        # https://stackoverflow.com/questions/2264428/converting-string-to-lower-case-in-bash#2264537
        - export NAMESPACE="$(echo "${CI_PROJECT_NAMESPACE}" | tr A-Z a-z)"
        - export IMAGE="${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}/nightly:master"
        - export OCI_YML=gnome-master.yml
    <<: *base_build

rust:master:
    stage: sdk_bundles
    before_script:
        # https://stackoverflow.com/questions/2264428/converting-string-to-lower-case-in-bash#2264537
        - export NAMESPACE="$(echo "${CI_PROJECT_NAMESPACE}" | tr A-Z a-z)"
        - export IMAGE="${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}/rust-bundle"
        - export OCI_YML=rust_extension.yml
    <<: *base_build
